mybatis-plus:
    mapper-locations: classpath*:/mapper/**/*Mapper.xml
    type-aliases-package: xyz.liuyou.seckill.pojo
spring:
    # 静态资源处理
    resources:
        # 启用默认静态资源处理，默认启用
        add-mappings: true
        cache:
            cachecontrol:
                #缓存响应时间，单位秒
                max-age: 3600
        chain:
            # 资源链中启用缓存，默认启用
            cache: true
            # 启用资源链，默认禁用
            enabled: true
            # 启用压缩资源(gzip,brotli)解析,默认禁用
            compressed: true
            # 启用H5应用缓存，默认禁用
            html-application-cache: true
        # 静态资源位置
        static-locations: classpath:/static/
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: mysql
        url: jdbc:mysql://localhost:3306/seckill?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        hikari:
            auto-commit: true
            connection-test-query: select 1
            connection-timeout: 30000
            idle-timeout: 1800000
            max-lifetime: 1800000
            maximum-pool-size: 10
            minimum-idle: 5
            pool-name: HikariCP
    thymeleaf:
        cache: false
    redis:
        host: 192.168.111.11
        port: 6379
        database: 0
        lettuce:
            pool:
                max-active: 8
                max-wait: 10000ms
                min-idle: 0
                max-idle: 8
        timeout: 10000ms
    rabbitmq:
        # 服务器地址
        host: 192.168.111.11
        # 用户名
        username: liuyou
        # 密码
        password: lmk
        # 虚拟主机
        virtual-host: /
        # 端口
        port: 5672
        listener:
          simple:
              # 消费者最小数量
              concurrency: 10
              # 消费者最大数量
              max-concurrency: 10
              # 限制消费者每次只处理一条消息，处理完再继续下一条消息
              prefetch: 1
              # 启动时是否默认启动容器，默认true
              auto-startup: true
              # 被拒绝时重新进入队列
              default-requeue-rejected: true
        template:
          retry:
              # 发布重试，默认false
              enabled: true
              # 重试时间，默认1000ms
              initial-interval: 1000ms
              # 重试最大次数，默认3次
              max-attempts: 3
              # 重试最大间隔时间，默认10000ms
              max-interval: 10000
              # 重试间隔的乘数，比如2.0，第一次等10s，第二次等20s，第三次等40s
              multiplier: 1.0





